# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 15:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                (
                    'consumable',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Consumable')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consumableincome', models.ManyToManyField(to='products.ConsumableIncome')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RemainingConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                (
                    'consumable',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Consumable')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportConsmable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                (
                    'consumable',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Consumable')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='report',
            name='reportconsumable',
            field=models.ManyToManyField(to='products.ReportConsmable'),
        ),
        migrations.AddField(
            model_name='report',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
