# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:14
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0002_restaurant_slug'),
        ('products', '0003_auto_20160910_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 9, 10, 20, 14, 10, 698813))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 20, 14, 10, 698303)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 20, 14, 10, 700372)),
        ),
    ]
