# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 12:15
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_auto_20160911_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 12, 15, 54, 758451)),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 12, 15, 54, 757882)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.ManyToManyField(to='products.Quantity'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 12, 15, 54, 760256)),
        ),
    ]
