# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:41
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_auto_20160911_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 21, 41, 46, 661587)),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 17)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 21, 41, 46, 663366)),
        ),
    ]
