# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:39
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0007_auto_20160917_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 26, 18, 39, 42, 270466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 9, 26, 18, 39, 42, 269993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 26, 18, 39, 42, 271948)),
        ),
    ]
