# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 13:18
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0009_auto_20160926_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 13, 17, 46, 176810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 13, 17, 46, 176328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 13, 17, 46, 177596)),
        ),
    ]
