# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 13:11
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0010_auto_20161001_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 8, 13, 11, 22, 629875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 8, 13, 11, 22, 629387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 8, 13, 11, 22, 630659)),
        ),
    ]
