# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:32
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0002_restaurant_slug'),
        ('products', '0011_auto_20161008_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reportconsumable',
        ),
        migrations.RemoveField(
            model_name='report',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='reportconsmable',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 13, 32, 23, 986694, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reportconsmable',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='restaurants.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 13, 32, 23, 986222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 13, 32, 23, 985739, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
