# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0013_auto_20161025_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remainingconsumable',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='remainingconsumable',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='remainingconsumable',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumableincome',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reportconsmable',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='RemainingConsumable',
        ),
    ]
